# .github/workflows/pr-check.yml
name: Check PR source branch

on:
  pull_request:
    branches: [main]

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from develop
        run: |
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "❌ Pull requests to main must come from develop branch"
            exit 1
          fi
